[tox]
minversion = 4.22
envlist =
    lint
    {py310,py311,py312,py313,py314}{,-mistune0}
    py311-noutils
    py311-tzdata
    cover-{clean,report}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
commands =
    {env:command_prefix:} coverage run -m pytest {posargs:tests -ra --durations=20}
passenv = USERNAME
setenv =
    # skip building frontend js/css
    HATCH_BUILD_NO_HOOKS=true
    # do not run marked slow tests in every variant testenv
    {mistune0,noutils,tzdata}: PYTEST_ADDOPTS=-m "not slowtest"
    # To test in environment without external utitilities like ffmpeg and git installed,
    # break PATH in noutils environment(s).
    noutils: command_prefix=env PATH="{env_bin_dir}"
dependency_groups =
    pytest
    mistune0: mistune0
    tzdata: tzdata
allowlist_externals = env
depends =
    py{310,311,312,313,314}: cover-clean
    cover-report: py{310,311,312,313,314}{,-mistune0,-noutils,-tzdata}
# XXX: I've been experiencing sporadic failures when running tox in parallel mode.
# The crux of the error messages when this happens appears to be something like:
#
#     WARNING: Skipping page https://pypi.org/simple/coverage/ because the GET request
#         got Content-Type: Unknown. The only supported Content-Types are
#         application/vnd.pypi.simple.v1+json, application/vnd.pypi.simple.v1+html, and
#         text/html
#
#     ERROR: Could not find a version that satisfies the requirement
#         coverage[toml] (from versions: none)
#
# It may be this issue: https://github.com/pypa/pip/issues/11340
#
# Setting download=true — which tells tox to upgrade pip to the latest version —
# seems to fix the issue for me.
#
# Hopefully, at some point this can be removed.
download = true

[testenv:lint]
base_python = py314,py313,py312,py311,py310
use_develop = true
dependency_groups = pylint
commands =
    pylint {posargs:lektor tests}

[testenv:cover-clean]
deps = coverage[toml]
skip_install = true
commands = coverage erase

[testenv:cover-report]
deps = coverage[toml]
skip_install = true
commands =
    -coverage combine --append
    coverage xml
    coverage report
